/* eslint-disable */
import { DateTime } from 'luxon';

/* Get the current instant */
const now = DateTime.now();

export const products = [
    // Anillos
    {
        id: '7eb7c859-1347-4317-96b6-9476a7e2ba3c',
        category: 'Anillos',
        name: 'Anillo Dreamer Ajustable',
        ref: '13007',
        stock: 30,
        precioDetal: 50000,
        precioEmprendedor: 45000,
        thumbnail: 'assets/images/apps/ecommerce/products/watch-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/watch-01-01.jpg',
            'assets/images/apps/ecommerce/products/watch-01-02.jpg',
            'assets/images/apps/ecommerce/products/watch-01-03.jpg',
        ],
    },
    {
        id: '8cb5c967-5678-4562-8749-9486c9e3ba7b',
        category: 'Anillos',
        name: 'Anillo Powerfull Ajustable',
        ref: '13001',
        stock: 25,
        precioDetal: 80000,
        precioEmprendedor: 50000,
        thumbnail: 'assets/images/apps/ecommerce/products/ring-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/ring-01-01.jpg',
            'assets/images/apps/ecommerce/products/ring-01-02.jpg',
        ],
    },
    {
        id: '3ab6d859-8953-4371-85b6-8356a8e3ba4d',
        category: 'Anillos',
        name: 'Anillo Elegance Dorado',
        ref: '13002',
        stock: 40,
        precioDetal: 75000,
        precioEmprendedor: 45000,
        thumbnail: 'assets/images/apps/ecommerce/products/ring-02-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/ring-02-01.jpg',
            'assets/images/apps/ecommerce/products/ring-02-02.jpg',
        ],
    },
    {
        id: '4cb7c859-5678-4317-92b6-9486a7e2ba3d',
        category: 'Anillos',
        name: 'Anillo Eternity Plata',
        ref: '13003',
        stock: 35,
        precioDetal: 95000,
        precioEmprendedor: 60000,
        thumbnail: 'assets/images/apps/ecommerce/products/ring-03-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/ring-03-01.jpg',
            'assets/images/apps/ecommerce/products/ring-03-02.jpg',
        ],
    },
    {
        id: '5dc7c859-1347-4317-91b6-9376a7e2ba3e',
        category: 'Anillos',
        name: 'Anillo Harmony Cristal',
        ref: '13004',
        stock: 20,
        precioDetal: 82000,
        precioEmprendedor: 52000,
        thumbnail: 'assets/images/apps/ecommerce/products/ring-04-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/ring-04-01.jpg',
            'assets/images/apps/ecommerce/products/ring-04-02.jpg',
        ],
    },
    {
        id: '6ec7c859-1347-4317-96b6-9376a7e2ba3f',
        category: 'Anillos',
        name: 'Anillo Romance Rubí',
        ref: '13005',
        stock: 50,
        precioDetal: 78000,
        precioEmprendedor: 48000,
        thumbnail: 'assets/images/apps/ecommerce/products/ring-05-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/ring-05-01.jpg',
            'assets/images/apps/ecommerce/products/ring-05-02.jpg',
        ],
    },
    {
        id: '7fc7c859-1347-4317-96b6-9376a7e2ba3g',
        category: 'Anillos',
        name: 'Anillo Glamour Zafiro',
        ref: '13006',
        stock: 15,
        precioDetal: 87000,
        precioEmprendedor: 57000,
        thumbnail: 'assets/images/apps/ecommerce/products/ring-06-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/ring-06-01.jpg',
            'assets/images/apps/ecommerce/products/ring-06-02.jpg',
        ],
    },
    {
        id: '8gc7c859-1347-4317-96b6-9376a7e2ba3h',
        category: 'Anillos',
        name: 'Anillo Mystic Ópalo',
        ref: '13007',
        stock: 10,
        precioDetal: 83000,
        precioEmprendedor: 53000,
        thumbnail: 'assets/images/apps/ecommerce/products/ring-07-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/ring-07-01.jpg',
            'assets/images/apps/ecommerce/products/ring-07-02.jpg',
        ],
    },
    {
        id: '9hc7c859-1347-4317-96b6-9376a7e2ba3i',
        category: 'Anillos',
        name: 'Anillo Radiance Diamante',
        ref: '13008',
        stock: 5,
        precioDetal: 115000,
        precioEmprendedor: 75000,
        thumbnail: 'assets/images/apps/ecommerce/products/ring-08-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/ring-08-01.jpg',
            'assets/images/apps/ecommerce/products/ring-08-02.jpg',
        ],
    },
    {
        id: '0ic7c859-1347-4317-96b6-9376a7e2ba3j',
        category: 'Anillos',
        name: 'Anillo Nature Esmeralda',
        ref: '13009',
        stock: 60,
        precioDetal: 79000,
        precioEmprendedor: 49000,
        thumbnail: 'assets/images/apps/ecommerce/products/ring-09-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/ring-09-01.jpg',
            'assets/images/apps/ecommerce/products/ring-09-02.jpg',
        ],
    },
    {
        id: '1jc7c859-1347-4317-96b6-9376a7e2ba3k',
        category: 'Anillos',
        name: 'Anillo Bold Onix',
        ref: '13010',
        stock: 45,
        precioDetal: 76000,
        precioEmprendedor: 46000,
        thumbnail: 'assets/images/apps/ecommerce/products/ring-10-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/ring-10-01.jpg',
            'assets/images/apps/ecommerce/products/ring-10-02.jpg',
        ],
    },
    // Aretes
    {
        id: '2kc7c859-1347-4317-96b6-9376a7e2ba3l',
        category: 'Aretes',
        name: 'Aretes Monarchy Verde Ajustable',
        ref: '23001',
        stock: 25,
        precioDetal: 50000,
        precioEmprendedor: 30000,
        thumbnail: 'assets/images/apps/ecommerce/products/earring-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/earring-01-01.jpg',
            'assets/images/apps/ecommerce/products/earring-01-02.jpg',
        ],
    },
    {
        id: '3lc7c859-1347-4317-96b6-9376a7e2ba3m',
        category: 'Aretes',
        name: 'Aretes Classic Oro',
        ref: '23002',
        stock: 20,
        precioDetal: 52000,
        precioEmprendedor: 32000,
        thumbnail: 'assets/images/apps/ecommerce/products/earring-02-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/earring-02-01.jpg',
            'assets/images/apps/ecommerce/products/earring-02-02.jpg',
        ],
    },
    {
        id: '4mc7c859-1347-4317-96b6-9376a7e2ba3n',
        category: 'Aretes',
        name: 'Aretes Sparkle Plata',
        ref: '23003',
        stock: 30,
        precioDetal: 55000,
        precioEmprendedor: 35000,
        thumbnail: 'assets/images/apps/ecommerce/products/earring-03-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/earring-03-01.jpg',
            'assets/images/apps/ecommerce/products/earring-03-02.jpg',
        ],
    },
    {
        id: '5nc7c859-1347-4317-96b6-9376a7e2ba3o',
        category: 'Aretes',
        name: 'Aretes Royal Rubí',
        ref: '23004',
        stock: 15,
        precioDetal: 57000,
        precioEmprendedor: 37000,
        thumbnail: 'assets/images/apps/ecommerce/products/earring-04-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/earring-04-01.jpg',
            'assets/images/apps/ecommerce/products/earring-04-02.jpg',
        ],
    },
    {
        id: '6oc7c859-1347-4317-96b6-9376a7e2ba3p',
        category: 'Aretes',
        name: 'Aretes Grace Zafiro',
        ref: '23005',
        stock: 10,
        precioDetal: 54000,
        precioEmprendedor: 34000,
        thumbnail: 'assets/images/apps/ecommerce/products/earring-05-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/earring-05-01.jpg',
            'assets/images/apps/ecommerce/products/earring-05-02.jpg',
        ],
    },
    {
        id: '7pc7c859-1347-4317-96b6-9376a7e2ba3q',
        category: 'Aretes',
        name: 'Aretes Elegance Cristal',
        ref: '23006',
        stock: 35,
        precioDetal: 53000,
        precioEmprendedor: 33000,
        thumbnail: 'assets/images/apps/ecommerce/products/earring-06-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/earring-06-01.jpg',
            'assets/images/apps/ecommerce/products/earring-06-02.jpg',
        ],
    },
    {
        id: '8qc7c859-1347-4317-96b6-9376a7e2ba3r',
        category: 'Aretes',
        name: 'Aretes Delight Ópalo',
        ref: '23007',
        stock: 40,
        precioDetal: 56000,
        precioEmprendedor: 36000,
        thumbnail: 'assets/images/apps/ecommerce/products/earring-07-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/earring-07-01.jpg',
            'assets/images/apps/ecommerce/products/earring-07-02.jpg',
        ],
    },
    {
        id: '9rc7c859-1347-4317-96b6-9376a7e2ba3s',
        category: 'Aretes',
        name: 'Aretes Prestige Diamante',
        ref: '23008',
        stock: 50,
        precioDetal: 60000,
        precioEmprendedor: 40000,
        thumbnail: 'assets/images/apps/ecommerce/products/earring-08-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/earring-08-01.jpg',
            'assets/images/apps/ecommerce/products/earring-08-02.jpg',
        ],
    },
    {
        id: '0sc7c859-1347-4317-96b6-9376a7e2ba3t',
        category: 'Aretes',
        name: 'Aretes Glam Esmeralda',
        ref: '23009',
        stock: 45,
        precioDetal: 51000,
        precioEmprendedor: 31000,
        thumbnail: 'assets/images/apps/ecommerce/products/earring-09-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/earring-09-01.jpg',
            'assets/images/apps/ecommerce/products/earring-09-02.jpg',
        ],
    },
    {
        id: '1tc7c859-1347-4317-96b6-9376a7e2ba3u',
        category: 'Aretes',
        name: 'Aretes Charm Onix',
        ref: '23010',
        stock: 20,
        precioDetal: 49000,
        precioEmprendedor: 29000,
        thumbnail: 'assets/images/apps/ecommerce/products/earring-10-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/earring-10-01.jpg',
            'assets/images/apps/ecommerce/products/earring-10-02.jpg',
        ],
    },
    // Cadenas
    {
        id: '2uc7c859-1347-4317-96b6-9376a7e2ba3v',
        category: 'Cadenas',
        name: 'Cadena Elegance Oro',
        ref: '33001',
        stock: 30,
        precioDetal: 120000,
        precioEmprendedor: 75000,
        thumbnail: 'assets/images/apps/ecommerce/products/chain-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/chain-01-01.jpg',
            'assets/images/apps/ecommerce/products/chain-01-02.jpg',
        ],
    },
    {
        id: '3vc7c859-1347-4317-96b6-9376a7e2ba3w',
        category: 'Cadenas',
        name: 'Cadena Serenity Plata',
        ref: '33002',
        stock: 20,
        precioDetal: 115000,
        precioEmprendedor: 70000,
        thumbnail: 'assets/images/apps/ecommerce/products/chain-02-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/chain-02-01.jpg',
            'assets/images/apps/ecommerce/products/chain-02-02.jpg',
        ],
    },
    {
        id: '4wc7c859-1347-4317-96b6-9376a7e2ba3x',
        category: 'Cadenas',
        name: 'Cadena Glamour Rubí',
        ref: '33003',
        stock: 25,
        precioDetal: 130000,
        precioEmprendedor: 80000,
        thumbnail: 'assets/images/apps/ecommerce/products/chain-03-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/chain-03-01.jpg',
            'assets/images/apps/ecommerce/products/chain-03-02.jpg',
        ],
    },
    {
        id: '5xc7c859-1347-4317-96b6-9376a7e2ba3y',
        category: 'Cadenas',
        name: 'Cadena Classic Zafiro',
        ref: '33004',
        stock: 10,
        precioDetal: 118000,
        precioEmprendedor: 72000,
        thumbnail: 'assets/images/apps/ecommerce/products/chain-04-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/chain-04-01.jpg',
            'assets/images/apps/ecommerce/products/chain-04-02.jpg',
        ],
    },
    {
        id: '6yc7c859-1347-4317-96b6-9376a7e2ba3z',
        category: 'Cadenas',
        name: 'Cadena Mystic Cristal',
        ref: '33005',
        stock: 35,
        precioDetal: 112000,
        precioEmprendedor: 68000,
        thumbnail: 'assets/images/apps/ecommerce/products/chain-05-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/chain-05-01.jpg',
            'assets/images/apps/ecommerce/products/chain-05-02.jpg',
        ],
    },
    {
        id: '7zc7c859-1347-4317-96b6-9376a7e2ba4a',
        category: 'Cadenas',
        name: 'Cadena Radiance Ópalo',
        ref: '33006',
        stock: 45,
        precioDetal: 123000,
        precioEmprendedor: 73000,
        thumbnail: 'assets/images/apps/ecommerce/products/chain-06-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/chain-06-01.jpg',
            'assets/images/apps/ecommerce/products/chain-06-02.jpg',
        ],
    },
    {
        id: '8ac7c859-1347-4317-96b6-9376a7e2ba4b',
        category: 'Cadenas',
        name: 'Cadena Bold Diamante',
        ref: '33007',
        stock: 60,
        precioDetal: 145000,
        precioEmprendedor: 90000,
        thumbnail: 'assets/images/apps/ecommerce/products/chain-07-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/chain-07-01.jpg',
            'assets/images/apps/ecommerce/products/chain-07-02.jpg',
        ],
    },
    {
        id: '9bc7c859-1347-4317-96b6-9376a7e2ba4c',
        category: 'Cadenas',
        name: 'Cadena Nature Esmeralda',
        ref: '33008',
        stock: 15,
        precioDetal: 125000,
        precioEmprendedor: 76000,
        thumbnail: 'assets/images/apps/ecommerce/products/chain-08-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/chain-08-01.jpg',
            'assets/images/apps/ecommerce/products/chain-08-02.jpg',
        ],
    },
    {
        id: '0cc7c859-1347-4317-96b6-9376a7e2ba4d',
        category: 'Cadenas',
        name: 'Cadena Prestige Onix',
        ref: '33009',
        stock: 10,
        precioDetal: 110000,
        precioEmprendedor: 67000,
        thumbnail: 'assets/images/apps/ecommerce/products/chain-09-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/chain-09-01.jpg',
            'assets/images/apps/ecommerce/products/chain-09-02.jpg',
        ],
    },
    {
        id: '1dc7c859-1347-4317-96b6-9376a7e2ba4e',
        category: 'Cadenas',
        name: 'Cadena Luxe Oro Rosa',
        ref: '33010',
        stock: 50,
        precioDetal: 135000,
        precioEmprendedor: 82000,
        thumbnail: 'assets/images/apps/ecommerce/products/chain-10-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/chain-10-01.jpg',
            'assets/images/apps/ecommerce/products/chain-10-02.jpg',
        ],
    },
    // Cruceros
    {
        id: '2ec7c859-1347-4317-96b6-9376a7e2ba4f',
        category: 'Cruceros',
        name: 'Crucero Faith Oro',
        ref: '43001',
        stock: 20,
        precioDetal: 65000,
        precioEmprendedor: 40000,
        thumbnail: 'assets/images/apps/ecommerce/products/crucifix-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/crucifix-01-01.jpg',
            'assets/images/apps/ecommerce/products/crucifix-01-02.jpg',
        ],
    },
    {
        id: '3fc7c859-1347-4317-96b6-9376a7e2ba4g',
        category: 'Cruceros',
        name: 'Crucero Hope Plata',
        ref: '43002',
        stock: 30,
        precioDetal: 60000,
        precioEmprendedor: 37000,
        thumbnail: 'assets/images/apps/ecommerce/products/crucifix-02-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/crucifix-02-01.jpg',
            'assets/images/apps/ecommerce/products/crucifix-02-02.jpg',
        ],
    },
    {
        id: '4gc7c859-1347-4317-96b6-9376a7e2ba4h',
        category: 'Cruceros',
        name: 'Crucero Devotion Rubí',
        ref: '43003',
        stock: 15,
        precioDetal: 67000,
        precioEmprendedor: 42000,
        thumbnail: 'assets/images/apps/ecommerce/products/crucifix-03-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/crucifix-03-01.jpg',
            'assets/images/apps/ecommerce/products/crucifix-03-02.jpg',
        ],
    },
    {
        id: '5hc7c859-1347-4317-96b6-9376a7e2ba4i',
        category: 'Cruceros',
        name: 'Crucero Serenity Zafiro',
        ref: '43004',
        stock: 25,
        precioDetal: 63000,
        precioEmprendedor: 39000,
        thumbnail: 'assets/images/apps/ecommerce/products/crucifix-04-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/crucifix-04-01.jpg',
            'assets/images/apps/ecommerce/products/crucifix-04-02.jpg',
        ],
    },
    {
        id: '6ic7c859-1347-4317-96b6-9376a7e2ba4j',
        category: 'Cruceros',
        name: 'Crucero Grace Cristal',
        ref: '43005',
        stock: 30,
        precioDetal: 62000,
        precioEmprendedor: 38000,
        thumbnail: 'assets/images/apps/ecommerce/products/crucifix-05-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/crucifix-05-01.jpg',
            'assets/images/apps/ecommerce/products/crucifix-05-02.jpg',
        ],
    },
    {
        id: '7jc7c859-1347-4317-96b6-9376a7e2ba4k',
        category: 'Cruceros',
        name: 'Crucero Radiance Ópalo',
        ref: '43006',
        stock: 40,
        precioDetal: 66000,
        precioEmprendedor: 41000,
        thumbnail: 'assets/images/apps/ecommerce/products/crucifix-06-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/crucifix-06-01.jpg',
            'assets/images/apps/ecommerce/products/crucifix-06-02.jpg',
        ],
    },
    {
        id: '8kc7c859-1347-4317-96b6-9376a7e2ba4l',
        category: 'Cruceros',
        name: 'Crucero Bold Diamante',
        ref: '43007',
        stock: 35,
        precioDetal: 70000,
        precioEmprendedor: 45000,
        thumbnail: 'assets/images/apps/ecommerce/products/crucifix-07-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/crucifix-07-01.jpg',
            'assets/images/apps/ecommerce/products/crucifix-07-02.jpg',
        ],
    },
    {
        id: '9lc7c859-1347-4317-96b6-9376a7e2ba4m',
        category: 'Cruceros',
        name: 'Crucero Harmony Esmeralda',
        ref: '43008',
        stock: 20,
        precioDetal: 65000,
        precioEmprendedor: 40000,
        thumbnail: 'assets/images/apps/ecommerce/products/crucifix-08-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/crucifix-08-01.jpg',
            'assets/images/apps/ecommerce/products/crucifix-08-02.jpg',
        ],
    },
    {
        id: '0mc7c859-1347-4317-96b6-9376a7e2ba4n',
        category: 'Cruceros',
        name: 'Crucero Prestige Onix',
        ref: '43009',
        stock: 10,
        precioDetal: 60000,
        precioEmprendedor: 36000,
        thumbnail: 'assets/images/apps/ecommerce/products/crucifix-09-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/crucifix-09-01.jpg',
            'assets/images/apps/ecommerce/products/crucifix-09-02.jpg',
        ],
    },
    {
        id: '1nc7c859-1347-4317-96b6-9376a7e2ba4o',
        category: 'Cruceros',
        name: 'Crucero Luxe Oro Rosa',
        ref: '43010',
        stock: 50,
        precioDetal: 67000,
        precioEmprendedor: 42000,
        thumbnail: 'assets/images/apps/ecommerce/products/crucifix-10-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/crucifix-10-01.jpg',
            'assets/images/apps/ecommerce/products/crucifix-10-02.jpg',
        ],
    },
    // Dijes
    {
        id: '2oc7c859-1347-4317-96b6-9376a7e2ba4p',
        category: 'Dijes',
        name: 'Dije Heart Oro',
        ref: '53001',
        stock: 20,
        precioDetal: 40000,
        precioEmprendedor: 25000,
        thumbnail: 'assets/images/apps/ecommerce/products/pendant-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/pendant-01-01.jpg',
            'assets/images/apps/ecommerce/products/pendant-01-02.jpg',
        ],
    },
    {
        id: '3pc7c859-1347-4317-96b6-9376a7e2ba4q',
        category: 'Dijes',
        name: 'Dije Star Plata',
        ref: '53002',
        stock: 25,
        precioDetal: 38000,
        precioEmprendedor: 23000,
        thumbnail: 'assets/images/apps/ecommerce/products/pendant-02-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/pendant-02-01.jpg',
            'assets/images/apps/ecommerce/products/pendant-02-02.jpg',
        ],
    },
    {
        id: '4qc7c859-1347-4317-96b6-9376a7e2ba4r',
        category: 'Dijes',
        name: 'Dije Moon Rubí',
        ref: '53003',
        stock: 30,
        precioDetal: 42000,
        precioEmprendedor: 27000,
        thumbnail: 'assets/images/apps/ecommerce/products/pendant-03-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/pendant-03-01.jpg',
            'assets/images/apps/ecommerce/products/pendant-03-02.jpg',
        ],
    },
    {
        id: '5rc7c859-1347-4317-96b6-9376a7e2ba4s',
        category: 'Dijes',
        name: 'Dije Sun Zafiro',
        ref: '53004',
        stock: 15,
        precioDetal: 41000,
        precioEmprendedor: 26000,
        thumbnail: 'assets/images/apps/ecommerce/products/pendant-04-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/pendant-04-01.jpg',
            'assets/images/apps/ecommerce/products/pendant-04-02.jpg',
        ],
    },
    {
        id: '6sc7c859-1347-4317-96b6-9376a7e2ba4t',
        category: 'Dijes',
        name: 'Dije Flower Cristal',
        ref: '53005',
        stock: 25,
        precioDetal: 39000,
        precioEmprendedor: 24000,
        thumbnail: 'assets/images/apps/ecommerce/products/pendant-05-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/pendant-05-01.jpg',
            'assets/images/apps/ecommerce/products/pendant-05-02.jpg',
        ],
    },
    {
        id: '7tc7c859-1347-4317-96b6-9376a7e2ba4u',
        category: 'Dijes',
        name: 'Dije Butterfly Ópalo',
        ref: '53006',
        stock: 20,
        precioDetal: 40000,
        precioEmprendedor: 25000,
        thumbnail: 'assets/images/apps/ecommerce/products/pendant-06-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/pendant-06-01.jpg',
            'assets/images/apps/ecommerce/products/pendant-06-02.jpg',
        ],
    },
    {
        id: '8uc7c859-1347-4317-96b6-9376a7e2ba4v',
        category: 'Dijes',
        name: 'Dije Leaf Diamante',
        ref: '53007',
        stock: 10,
        precioDetal: 45000,
        precioEmprendedor: 28000,
        thumbnail: 'assets/images/apps/ecommerce/products/pendant-07-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/pendant-07-01.jpg',
            'assets/images/apps/ecommerce/products/pendant-07-02.jpg',
        ],
    },
    {
        id: '9vc7c859-1347-4317-96b6-9376a7e2ba4w',
        category: 'Dijes',
        name: 'Dije Bird Esmeralda',
        ref: '53008',
        stock: 35,
        precioDetal: 40000,
        precioEmprendedor: 25000,
        thumbnail: 'assets/images/apps/ecommerce/products/pendant-08-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/pendant-08-01.jpg',
            'assets/images/apps/ecommerce/products/pendant-08-02.jpg',
        ],
    },
    {
        id: '0wc7c859-1347-4317-96b6-9376a7e2ba4x',
        category: 'Dijes',
        name: 'Dije Clover Onix',
        ref: '53009',
        stock: 20,
        precioDetal: 38000,
        precioEmprendedor: 23000,
        thumbnail: 'assets/images/apps/ecommerce/products/pendant-09-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/pendant-09-01.jpg',
            'assets/images/apps/ecommerce/products/pendant-09-02.jpg',
        ],
    },
    {
        id: '1xc7c859-1347-4317-96b6-9376a7e2ba4y',
        category: 'Dijes',
        name: 'Dije Starfish Cristal',
        ref: '53010',
        stock: 15,
        precioDetal: 36000,
        precioEmprendedor: 22000,
        thumbnail: 'assets/images/apps/ecommerce/products/pendant-10-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/pendant-10-01.jpg',
            'assets/images/apps/ecommerce/products/pendant-10-02.jpg',
        ],
    },
    // Exclusividades
    {
        id: '2yc7c859-1347-4317-96b6-9376a7e2ba4z',
        category: 'Exclusividades',
        name: 'Exclusivo Royal Crown',
        ref: '63001',
        stock: 10,
        precioDetal: 220000,
        precioEmprendedor: 150000,
        thumbnail: 'assets/images/apps/ecommerce/products/exclusive-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/exclusive-01-01.jpg',
            'assets/images/apps/ecommerce/products/exclusive-01-02.jpg',
        ],
    },
    {
        id: '3zc7c859-1347-4317-96b6-9376a7e2ba5a',
        category: 'Exclusividades',
        name: 'Exclusivo Imperial Necklace',
        ref: '63002',
        stock: 15,
        precioDetal: 210000,
        precioEmprendedor: 140000,
        thumbnail: 'assets/images/apps/ecommerce/products/exclusive-02-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/exclusive-02-01.jpg',
            'assets/images/apps/ecommerce/products/exclusive-02-02.jpg',
        ],
    },
    {
        id: '4ac7c859-1347-4317-96b6-9376a7e2ba5b',
        category: 'Exclusividades',
        name: 'Exclusivo Noble Ring',
        ref: '63003',
        stock: 20,
        precioDetal: 230000,
        precioEmprendedor: 160000,
        thumbnail: 'assets/images/apps/ecommerce/products/exclusive-03-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/exclusive-03-01.jpg',
            'assets/images/apps/ecommerce/products/exclusive-03-02.jpg',
        ],
    },
    {
        id: '5bc7c859-1347-4317-96b6-9376a7e2ba5c',
        category: 'Exclusividades',
        name: 'Exclusivo Regal Bracelet',
        ref: '63004',
        stock: 10,
        precioDetal: 225000,
        precioEmprendedor: 155000,
        thumbnail: 'assets/images/apps/ecommerce/products/exclusive-04-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/exclusive-04-01.jpg',
            'assets/images/apps/ecommerce/products/exclusive-04-02.jpg',
        ],
    },
    {
        id: '6cc7c859-1347-4317-96b6-9376a7e2ba5d',
        category: 'Exclusividades',
        name: 'Exclusivo Majesty Earrings',
        ref: '63005',
        stock: 15,
        precioDetal: 215000,
        precioEmprendedor: 145000,
        thumbnail: 'assets/images/apps/ecommerce/products/exclusive-05-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/exclusive-05-01.jpg',
            'assets/images/apps/ecommerce/products/exclusive-05-02.jpg',
        ],
    },
    {
        id: '7dc7c859-1347-4317-96b6-9376a7e2ba5e',
        category: 'Exclusividades',
        name: 'Exclusivo Sovereign Brooch',
        ref: '63006',
        stock: 20,
        precioDetal: 235000,
        precioEmprendedor: 165000,
        thumbnail: 'assets/images/apps/ecommerce/products/exclusive-06-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/exclusive-06-01.jpg',
            'assets/images/apps/ecommerce/products/exclusive-06-02.jpg',
        ],
    },
    {
        id: '8ec7c859-1347-4317-96b6-9376a7e2ba5f',
        category: 'Exclusividades',
        name: 'Exclusivo Aristocrat Pendant',
        ref: '63007',
        stock: 10,
        precioDetal: 240000,
        precioEmprendedor: 170000,
        thumbnail: 'assets/images/apps/ecommerce/products/exclusive-07-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/exclusive-07-01.jpg',
            'assets/images/apps/ecommerce/products/exclusive-07-02.jpg',
        ],
    },
    {
        id: '9fc7c859-1347-4317-96b6-9376a7e2ba5g',
        category: 'Exclusividades',
        name: 'Exclusivo Monarch Cufflinks',
        ref: '63008',
        stock: 15,
        precioDetal: 230000,
        precioEmprendedor: 160000,
        thumbnail: 'assets/images/apps/ecommerce/products/exclusive-08-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/exclusive-08-01.jpg',
            'assets/images/apps/ecommerce/products/exclusive-08-02.jpg',
        ],
    },
    {
        id: '0gc7c859-1347-4317-96b6-9376a7e2ba5h',
        category: 'Exclusividades',
        name: 'Exclusivo Empress Choker',
        ref: '63009',
        stock: 25,
        precioDetal: 220000,
        precioEmprendedor: 150000,
        thumbnail: 'assets/images/apps/ecommerce/products/exclusive-09-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/exclusive-09-01.jpg',
            'assets/images/apps/ecommerce/products/exclusive-09-02.jpg',
        ],
    },
    {
        id: '1hc7c859-1347-4317-96b6-9376a7e2ba5i',
        category: 'Exclusividades',
        name: 'Exclusivo Tsar Necklace',
        ref: '63010',
        stock: 10,
        precioDetal: 245000,
        precioEmprendedor: 175000,
        thumbnail: 'assets/images/apps/ecommerce/products/exclusive-10-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/exclusive-10-01.jpg',
            'assets/images/apps/ecommerce/products/exclusive-10-02.jpg',
        ],
    },
    // Herrajes
    {
        id: '2ic7c859-1347-4317-96b6-9376a7e2ba5j',
        category: 'Herrajes',
        name: 'Herraje Vintage Oro',
        ref: '73001',
        stock: 20,
        precioDetal: 80000,
        precioEmprendedor: 50000,
        thumbnail: 'assets/images/apps/ecommerce/products/fitting-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/fitting-01-01.jpg',
            'assets/images/apps/ecommerce/products/fitting-01-02.jpg',
        ],
    },
    {
        id: '3jc7c859-1347-4317-96b6-9376a7e2ba5k',
        category: 'Herrajes',
        name: 'Herraje Modern Plata',
        ref: '73002',
        stock: 15,
        precioDetal: 78000,
        precioEmprendedor: 48000,
        thumbnail: 'assets/images/apps/ecommerce/products/fitting-02-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/fitting-02-01.jpg',
            'assets/images/apps/ecommerce/products/fitting-02-02.jpg',
        ],
    },
    {
        id: '4kc7c859-1347-4317-96b6-9376a7e2ba5l',
        category: 'Herrajes',
        name: 'Herraje Classic Rubí',
        ref: '73003',
        stock: 30,
        precioDetal: 83000,
        precioEmprendedor: 53000,
        thumbnail: 'assets/images/apps/ecommerce/products/fitting-03-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/fitting-03-01.jpg',
            'assets/images/apps/ecommerce/products/fitting-03-02.jpg',
        ],
    },
    {
        id: '5lc7c859-1347-4317-96b6-9376a7e2ba5m',
        category: 'Herrajes',
        name: 'Herraje Elegant Zafiro',
        ref: '73004',
        stock: 25,
        precioDetal: 82000,
        precioEmprendedor: 52000,
        thumbnail: 'assets/images/apps/ecommerce/products/fitting-04-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/fitting-04-01.jpg',
            'assets/images/apps/ecommerce/products/fitting-04-02.jpg',
        ],
    },
    {
        id: '6mc7c859-1347-4317-96b6-9376a7e2ba5n',
        category: 'Herrajes',
        name: 'Herraje Chic Cristal',
        ref: '73005',
        stock: 20,
        precioDetal: 79000,
        precioEmprendedor: 49000,
        thumbnail: 'assets/images/apps/ecommerce/products/fitting-05-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/fitting-05-01.jpg',
            'assets/images/apps/ecommerce/products/fitting-05-02.jpg',
        ],
    },
    {
        id: '7nc7c859-1347-4317-96b6-9376a7e2ba5o',
        category: 'Herrajes',
        name: 'Herraje Bold Ópalo',
        ref: '73006',
        stock: 15,
        precioDetal: 81000,
        precioEmprendedor: 51000,
        thumbnail: 'assets/images/apps/ecommerce/products/fitting-06-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/fitting-06-01.jpg',
            'assets/images/apps/ecommerce/products/fitting-06-02.jpg',
        ],
    },
    {
        id: '8oc7c859-1347-4317-96b6-9376a7e2ba5p',
        category: 'Herrajes',
        name: 'Herraje Glam Diamante',
        ref: '73007',
        stock: 10,
        precioDetal: 85000,
        precioEmprendedor: 55000,
        thumbnail: 'assets/images/apps/ecommerce/products/fitting-07-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/fitting-07-01.jpg',
            'assets/images/apps/ecommerce/products/fitting-07-02.jpg',
        ],
    },
    {
        id: '9pc7c859-1347-4317-96b6-9376a7e2ba5q',
        category: 'Herrajes',
        name: 'Herraje Stylish Esmeralda',
        ref: '73008',
        stock: 25,
        precioDetal: 80000,
        precioEmprendedor: 50000,
        thumbnail: 'assets/images/apps/ecommerce/products/fitting-08-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/fitting-08-01.jpg',
            'assets/images/apps/ecommerce/products/fitting-08-02.jpg',
        ],
    },
    {
        id: '0qc7c859-1347-4317-96b6-9376a7e2ba5r',
        category: 'Herrajes',
        name: 'Herraje Luxe Onix',
        ref: '73009',
        stock: 20,
        precioDetal: 77000,
        precioEmprendedor: 47000,
        thumbnail: 'assets/images/apps/ecommerce/products/fitting-09-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/fitting-09-01.jpg',
            'assets/images/apps/ecommerce/products/fitting-09-02.jpg',
        ],
    },
    {
        id: '1rc7c859-1347-4317-96b6-9376a7e2ba5s',
        category: 'Herrajes',
        name: 'Herraje Prestige Oro Rosa',
        ref: '73010',
        stock: 15,
        precioDetal: 84000,
        precioEmprendedor: 54000,
        thumbnail: 'assets/images/apps/ecommerce/products/fitting-10-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/fitting-10-01.jpg',
            'assets/images/apps/ecommerce/products/fitting-10-02.jpg',
        ],
    },
    // Pulseras
    {
        id: '2sc7c859-1347-4317-96b6-9376a7e2ba5t',
        category: 'Pulseras',
        name: 'Pulsera Garden Ajustable',
        ref: '83001',
        stock: 30,
        precioDetal: 55000,
        precioEmprendedor: 35000,
        thumbnail: 'assets/images/apps/ecommerce/products/bracelet-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/bracelet-01-01.jpg',
            'assets/images/apps/ecommerce/products/bracelet-01-02.jpg',
        ],
    },
    {
        id: '3tc7c859-1347-4317-96b6-9376a7e2ba5u',
        category: 'Pulseras',
        name: 'Pulsera Elegance Plata',
        ref: '83002',
        stock: 25,
        precioDetal: 53000,
        precioEmprendedor: 33000,
        thumbnail: 'assets/images/apps/ecommerce/products/bracelet-02-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/bracelet-02-01.jpg',
            'assets/images/apps/ecommerce/products/bracelet-02-02.jpg',
        ],
    },
    {
        id: '4uc7c859-1347-4317-96b6-9376a7e2ba5v',
        category: 'Pulseras',
        name: 'Pulsera Charm Rubí',
        ref: '83003',
        stock: 20,
        precioDetal: 56000,
        precioEmprendedor: 36000,
        thumbnail: 'assets/images/apps/ecommerce/products/bracelet-03-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/bracelet-03-01.jpg',
            'assets/images/apps/ecommerce/products/bracelet-03-02.jpg',
        ],
    },
    {
        id: '5vc7c859-1347-4317-96b6-9376a7e2ba5w',
        category: 'Pulseras',
        name: 'Pulsera Glamour Zafiro',
        ref: '83004',
        stock: 15,
        precioDetal: 54000,
        precioEmprendedor: 34000,
        thumbnail: 'assets/images/apps/ecommerce/products/bracelet-04-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/bracelet-04-01.jpg',
            'assets/images/apps/ecommerce/products/bracelet-04-02.jpg',
        ],
    },
    {
        id: '6wc7c859-1347-4317-96b6-9376a7e2ba5x',
        category: 'Pulseras',
        name: 'Pulsera Radiance Cristal',
        ref: '83005',
        stock: 30,
        precioDetal: 52000,
        precioEmprendedor: 32000,
        thumbnail: 'assets/images/apps/ecommerce/products/bracelet-05-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/bracelet-05-01.jpg',
            'assets/images/apps/ecommerce/products/bracelet-05-02.jpg',
        ],
    },
    {
        id: '7xc7c859-1347-4317-96b6-9376a7e2ba5y',
        category: 'Pulseras',
        name: 'Pulsera Mystic Ópalo',
        ref: '83006',
        stock: 25,
        precioDetal: 55000,
        precioEmprendedor: 35000,
        thumbnail: 'assets/images/apps/ecommerce/products/bracelet-06-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/bracelet-06-01.jpg',
            'assets/images/apps/ecommerce/products/bracelet-06-02.jpg',
        ],
    },
    {
        id: '8yc7c859-1347-4317-96b6-9376a7e2ba5z',
        category: 'Pulseras',
        name: 'Pulsera Bold Diamante',
        ref: '83007',
        stock: 20,
        precioDetal: 57000,
        precioEmprendedor: 37000,
        thumbnail: 'assets/images/apps/ecommerce/products/bracelet-07-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/bracelet-07-01.jpg',
            'assets/images/apps/ecommerce/products/bracelet-07-02.jpg',
        ],
    },
    {
        id: '9zc7c859-1347-4317-96b6-9376a7e2ba6a',
        category: 'Pulseras',
        name: 'Pulsera Nature Esmeralda',
        ref: '83008',
        stock: 35,
        precioDetal: 54000,
        precioEmprendedor: 34000,
        thumbnail: 'assets/images/apps/ecommerce/products/bracelet-08-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/bracelet-08-01.jpg',
            'assets/images/apps/ecommerce/products/bracelet-08-02.jpg',
        ],
    },
    {
        id: '0ac7c859-1347-4317-96b6-9376a7e2ba6b',
        category: 'Pulseras',
        name: 'Pulsera Prestige Onix',
        ref: '83009',
        stock: 25,
        precioDetal: 51000,
        precioEmprendedor: 31000,
        thumbnail: 'assets/images/apps/ecommerce/products/bracelet-09-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/bracelet-09-01.jpg',
            'assets/images/apps/ecommerce/products/bracelet-09-02.jpg',
        ],
    },
        // Rosarios
    {
        id: '2bc7c859-1347-4317-96b6-9376a7e2ba6d',
        category: 'Rosarios',
        name: 'Rosario Devotion Oro',
        ref: '93001',
        stock: 20,
        precioDetal: 110000,
        precioEmprendedor: 70000,
        thumbnail: 'assets/images/apps/ecommerce/products/rosary-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/rosary-01-01.jpg',
            'assets/images/apps/ecommerce/products/rosary-01-02.jpg',
        ],
    },
    {
        id: '3cc7c859-1347-4317-96b6-9376a7e2ba6e',
        category: 'Rosarios',
        name: 'Rosario Faith Plata',
        ref: '93002',
        stock: 25,
        precioDetal: 108000,
        precioEmprendedor: 68000,
        thumbnail: 'assets/images/apps/ecommerce/products/rosary-02-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/rosary-02-01.jpg',
            'assets/images/apps/ecommerce/products/rosary-02-02.jpg',
        ],
    },
    {
        id: '4dc7c859-1347-4317-96b6-9376a7e2ba6f',
        category: 'Rosarios',
        name: 'Rosario Hope Rubí',
        ref: '93003',
        stock: 30,
        precioDetal: 115000,
        precioEmprendedor: 75000,
        thumbnail: 'assets/images/apps/ecommerce/products/rosary-03-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/rosary-03-01.jpg',
            'assets/images/apps/ecommerce/products/rosary-03-02.jpg',
        ],
    },
    {
        id: '5ec7c859-1347-4317-96b6-9376a7e2ba6g',
        category: 'Rosarios',
        name: 'Rosario Serenity Zafiro',
        ref: '93004',
        stock: 15,
        precioDetal: 112000,
        precioEmprendedor: 72000,
        thumbnail: 'assets/images/apps/ecommerce/products/rosary-04-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/rosary-04-01.jpg',
            'assets/images/apps/ecommerce/products/rosary-04-02.jpg',
        ],
    },
    {
        id: '6fc7c859-1347-4317-96b6-9376a7e2ba6h',
        category: 'Rosarios',
        name: 'Rosario Grace Cristal',
        ref: '93005',
        stock: 20,
        precioDetal: 110000,
        precioEmprendedor: 69000,
        thumbnail: 'assets/images/apps/ecommerce/products/rosary-05-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/rosary-05-01.jpg',
            'assets/images/apps/ecommerce/products/rosary-05-02.jpg',
        ],
    },
    {
        id: '7gc7c859-1347-4317-96b6-9376a7e2ba6i',
        category: 'Rosarios',
        name: 'Rosario Radiance Ópalo',
        ref: '93006',
        stock: 25,
        precioDetal: 113000,
        precioEmprendedor: 73000,
        thumbnail: 'assets/images/apps/ecommerce/products/rosary-06-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/rosary-06-01.jpg',
            'assets/images/apps/ecommerce/products/rosary-06-02.jpg',
        ],
    },
    {
        id: '8hc7c859-1347-4317-96b6-9376a7e2ba6j',
        category: 'Rosarios',
        name: 'Rosario Bold Diamante',
        ref: '93007',
        stock: 10,
        precioDetal: 120000,
        precioEmprendedor: 80000,
        thumbnail: 'assets/images/apps/ecommerce/products/rosary-07-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/rosary-07-01.jpg',
            'assets/images/apps/ecommerce/products/rosary-07-02.jpg',
        ],
    },
    {
        id: '9ic7c859-1347-4317-96b6-9376a7e2ba6k',
        category: 'Rosarios',
        name: 'Rosario Harmony Esmeralda',
        ref: '93008',
        stock: 15,
        precioDetal: 111000,
        precioEmprendedor: 71000,
        thumbnail: 'assets/images/apps/ecommerce/products/rosary-08-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/rosary-08-01.jpg',
            'assets/images/apps/ecommerce/products/rosary-08-02.jpg',
        ],
    },
    {
        id: '0jc7c859-1347-4317-96b6-9376a7e2ba6l',
        category: 'Rosarios',
        name: 'Rosario Prestige Onix',
        ref: '93009',
        stock: 20,
        precioDetal: 107000,
        precioEmprendedor: 67000,
        thumbnail: 'assets/images/apps/ecommerce/products/rosary-09-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/rosary-09-01.jpg',
            'assets/images/apps/ecommerce/products/rosary-09-02.jpg',
        ],
    },
    {
        id: '1kc7c859-1347-4317-96b6-9376a7e2ba6m',
        category: 'Rosarios',
        name: 'Rosario Luxe Oro Rosa',
        ref: '93010',
        stock: 25,
        precioDetal: 114000,
        precioEmprendedor: 74000,
        thumbnail: 'assets/images/apps/ecommerce/products/rosary-10-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/rosary-10-01.jpg',
            'assets/images/apps/ecommerce/products/rosary-10-02.jpg',
        ],
    },
    // Tobilleras
    {
        id: '2lc7c859-1347-4317-96b6-9376a7e2ba6n',
        category: 'Tobilleras',
        name: 'Tobillera Delicate Oro',
        ref: '103001',
        stock: 20,
        precioDetal: 35000,
        precioEmprendedor: 20000,
        thumbnail: 'assets/images/apps/ecommerce/products/anklet-01-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/anklet-01-01.jpg',
            'assets/images/apps/ecommerce/products/anklet-01-02.jpg',
        ],
    },
    {
        id: '3mc7c859-1347-4317-96b6-9376a7e2ba6o',
        category: 'Tobilleras',
        name: 'Tobillera Classic Plata',
        ref: '103002',
        stock: 15,
        precioDetal: 33000,
        precioEmprendedor: 18000,
        thumbnail: 'assets/images/apps/ecommerce/products/anklet-02-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/anklet-02-01.jpg',
            'assets/images/apps/ecommerce/products/anklet-02-02.jpg',
        ],
    },
    {
        id: '4nc7c859-1347-4317-96b6-9376a7e2ba6p',
        category: 'Tobilleras',
        name: 'Tobillera Spark Rubí',
        ref: '103003',
        stock: 25,
        precioDetal: 37000,
        precioEmprendedor: 22000,
        thumbnail: 'assets/images/apps/ecommerce/products/anklet-03-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/anklet-03-01.jpg',
            'assets/images/apps/ecommerce/products/anklet-03-02.jpg',
        ],
    },
    {
        id: '5oc7c859-1347-4317-96b6-9376a7e2ba6q',
        category: 'Tobilleras',
        name: 'Tobillera Shine Zafiro',
        ref: '103004',
        stock: 10,
        precioDetal: 36000,
        precioEmprendedor: 21000,
        thumbnail: 'assets/images/apps/ecommerce/products/anklet-04-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/anklet-04-01.jpg',
            'assets/images/apps/ecommerce/products/anklet-04-02.jpg',
        ],
    },
    {
        id: '6pc7c859-1347-4317-96b6-9376a7e2ba6r',
        category: 'Tobilleras',
        name: 'Tobillera Elegance Cristal',
        ref: '103005',
        stock: 30,
        precioDetal: 34000,
        precioEmprendedor: 19000,
        thumbnail: 'assets/images/apps/ecommerce/products/anklet-05-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/anklet-05-01.jpg',
            'assets/images/apps/ecommerce/products/anklet-05-02.jpg',
        ],
    },
    {
        id: '7qc7c859-1347-4317-96b6-9376a7e2ba6s',
        category: 'Tobilleras',
        name: 'Tobillera Glam Ópalo',
        ref: '103006',
        stock: 15,
        precioDetal: 35000,
        precioEmprendedor: 20000,
        thumbnail: 'assets/images/apps/ecommerce/products/anklet-06-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/anklet-06-01.jpg',
            'assets/images/apps/ecommerce/products/anklet-06-02.jpg',
        ],
    },
    {
        id: '8rc7c859-1347-4317-96b6-9376a7e2ba6t',
        category: 'Tobilleras',
        name: 'Tobillera Radiant Diamante',
        ref: '103007',
        stock: 25,
        precioDetal: 39000,
        precioEmprendedor: 24000,
        thumbnail: 'assets/images/apps/ecommerce/products/anklet-07-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/anklet-07-01.jpg',
            'assets/images/apps/ecommerce/products/anklet-07-02.jpg',
        ],
    },
    {
        id: '9sc7c859-1347-4317-96b6-9376a7e2ba6u',
        category: 'Tobilleras',
        name: 'Tobillera Nature Esmeralda',
        ref: '103008',
        stock: 20,
        precioDetal: 36000,
        precioEmprendedor: 21000,
        thumbnail: 'assets/images/apps/ecommerce/products/anklet-08-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/anklet-08-01.jpg',
            'assets/images/apps/ecommerce/products/anklet-08-02.jpg',
        ],
    },
    {
        id: '0tc7c859-1347-4317-96b6-9376a7e2ba6v',
        category: 'Tobilleras',
        name: 'Tobillera Charm Onix',
        ref: '103009',
        stock: 10,
        precioDetal: 32000,
        precioEmprendedor: 17000,
        thumbnail: 'assets/images/apps/ecommerce/products/anklet-09-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/anklet-09-01.jpg',
            'assets/images/apps/ecommerce/products/anklet-09-02.jpg',
        ],
    },
    {
        id: '1uc7c859-1347-4317-96b6-9376a7e2ba6w',
        category: 'Tobilleras',
        name: 'Tobillera Luxe Oro Rosa',
        ref: '103010',
        stock: 30,
        precioDetal: 38000,
        precioEmprendedor: 23000,
        thumbnail: 'assets/images/apps/ecommerce/products/anklet-10-thumb.jpg',
        images: [
            'assets/images/apps/ecommerce/products/anklet-10-01.jpg',
            'assets/images/apps/ecommerce/products/anklet-10-02.jpg',
        ],
    }
];

export const activities = [
    {
        id          : '493190c9-5b61-4912-afe5-78c21f1044d7',
        icon        : 'heroicons_solid:star',
        description : 'Your submission has been accepted',
        date        : now.minus({minutes: 25}).toISO(), // 25 minutes ago
        extraContent: `<div class="font-bold">Congratulations for your acceptance!</div><br>
                        <div>Hi Brian,<br>Your submission has been accepted and you are ready to move into the next phase. Once you are ready, reach out to me and we will ...</div>`,
    },
    {
        id           : '6e3e97e5-effc-4fb7-b730-52a151f0b641',
        image        : 'assets/images/avatars/male-04.jpg',
        description  : '<strong>Leo Gill</strong> added you to <strong>Top Secret Project</strong> group and assigned you as a <strong>Project Manager</strong>',
        date         : now.minus({minutes: 50}).toISO(), // 50 minutes ago
        linkedContent: 'Top Secret Project',
        link         : '/dashboards/project',
        useRouter    : true,
    },
    {
        id           : 'b91ccb58-b06c-413b-b389-87010e03a120',
        icon         : 'heroicons_solid:envelope',
        description  : 'You have 15 unread mails across 3 mailboxes',
        date         : now.minus({hours: 3}).toISO(), // 3 hours ago
        linkedContent: 'Mailbox',
        link         : '/apps/mailbox',
        useRouter    : true,
    },
    {
        id           : '541416c9-84a7-408a-8d74-27a43c38d797',
        icon         : 'heroicons_solid:arrow-path',
        description  : 'Your <strong>Docker container</strong> is ready to publish',
        date         : now.minus({hours: 5}).toISO(), // 5 hours ago
        linkedContent: 'Download the container',
        link         : '.',
        useRouter    : true,
    },
    {
        id          : 'ef7b95a7-8e8b-4616-9619-130d9533add9',
        image       : 'assets/images/avatars/male-06.jpg',
        description : '<strong>Roger Murray</strong> accepted your friend request',
        date        : now.minus({hours: 7}).toISO(), // 7 hours ago
        extraContent: `You have <span class="font-semibold">8</span> mutual friends.`,
    },
    {
        id         : 'eb8aa470-635e-461d-88e1-23d9ea2a5665',
        image      : 'assets/images/avatars/female-04.jpg',
        description: '<strong>Sophie Stone</strong> sent you a direct message',
        date       : now.minus({hours: 9}).toISO(), // 9 hours ago
    },
    {
        id           : 'b85c2338-cc98-4140-bbf8-c226ce4e395e',
        icon         : 'heroicons_solid:envelope',
        description  : 'You have 3 new mails',
        date         : now.minus({day: 1}).toISO(), // 1 day ago
        extraContent : `<ol class="list-decimal list-inside space-y-2">
                            <li class="font-medium">Please review and sign the attached agreement</li>
                            <li class="font-medium">Delivery address confirmation</li>
                            <li class="font-medium">Previous clients and their invoices</li>
                        </ol>`,
        linkedContent: 'Mailbox',
        link         : '/apps/mailbox',
        useRouter    : true,
    },
    {
        id           : 'fd0f01b4-f3de-4333-add5-cd86850279f8',
        image        : 'assets/images/avatars/female-02.jpg',
        description  : '<strong>Tina Harris</strong> started a chat with you',
        date         : now.minus({day: 1}).toISO(), // 1 day ago,
        linkedContent: 'Go to Chat (Tina Harris)',
        link         : '/apps/chat/5636c0ba-fa47-42ca-9160-27340583041e',
        useRouter    : true,
    },
    {
        id         : '8f8e1bf9-4661-4939-9e43-390957b60f42',
        icon       : 'heroicons_solid:star',
        description: 'Your submission has been accepted and you are ready to sign-up for the final assigment which will be ready in 2 days',
        date       : now.minus({days: 3}).toISO(), // 3 days ago
    },
    {
        id         : '30af917b-7a6a-45d1-822f-9e7ad7f8bf69',
        icon       : 'heroicons_solid:arrow-path',
        description: 'Your Vagrant container is ready to download',
        date       : now.minus({day: 4}).toISO(), // 4 days ago
    },
];
